host = "0.0.0.0:9090"
env = "prod"
v8_maxcount = 30
v8_lifetime = 3600
js_project_path = "jsproj"
static_url_path = "/static"
template_name = "ssr.prod.html"
internal_api_ip = "127.0.0.1"
internal_api_port = 80

[Log]
debug=false
filenum=20
filesize=256
filename="run"
level="INFO"
dir="/data/log/ssr_logs"
